// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAqzIN2u2Azfnl2Et9MqaHMvOWaBreHG8',
    appId: '1:434869212348:web:bb67551ddaab95b64cacb9',
    messagingSenderId: '434869212348',
    projectId: 'taskmanager-fce3b',
    authDomain: 'taskmanager-fce3b.firebaseapp.com',
    storageBucket: 'taskmanager-fce3b.appspot.com',
    measurementId: 'G-0LP0LY1T5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKexOvQhqkFvCrV_GOJrNXqRGj3gv5XDI',
    appId: '1:434869212348:android:8e5e58ec709cd4144cacb9',
    messagingSenderId: '434869212348',
    projectId: 'taskmanager-fce3b',
    storageBucket: 'taskmanager-fce3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aUgxqjLsFAQNFcXchIxXjPjXYMu6X18',
    appId: '1:434869212348:ios:f22b37f60d5e35804cacb9',
    messagingSenderId: '434869212348',
    projectId: 'taskmanager-fce3b',
    storageBucket: 'taskmanager-fce3b.appspot.com',
    iosClientId: '434869212348-v1emvss7nor4iggvfhlsqj0q598qlem6.apps.googleusercontent.com',
    iosBundleId: 'com.example.managerTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aUgxqjLsFAQNFcXchIxXjPjXYMu6X18',
    appId: '1:434869212348:ios:f22b37f60d5e35804cacb9',
    messagingSenderId: '434869212348',
    projectId: 'taskmanager-fce3b',
    storageBucket: 'taskmanager-fce3b.appspot.com',
    iosClientId: '434869212348-v1emvss7nor4iggvfhlsqj0q598qlem6.apps.googleusercontent.com',
    iosBundleId: 'com.example.managerTask',
  );
}
